W5D1/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :create, :new, :destroy, :show]
  resource :session, only: [:create, :destroy, :new]
  resources :albums, except: [:index]

  resources :bands

end

W5D1/MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  band_id    :string           not null
#  title      :string           not null
#  year       :date             not null
#  live       :boolean          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord

  validates :band_id, presence: true
  validates :title, presence: true
  validates :year, presence: true
  validates :live, presence: true

  belongs_to :band,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Band



  
end

W5D1/MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord

has_many :albums,
primary_key: :id,
foreign_key: :band_id,
class_name: :Album



end

W5D1/MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint(8)        not null, primary key
#  email            :string           not null
#  password_digrest :string           not null
#  session_token    :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  name             :string
#

class User < ApplicationRecord

  validates :email, presence: true, uniqueness: true
  validates :password_digrest, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password
  # validates :name
  validates :session_token, presence: true

  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password

    self.password_digrest = BCrypt::Password.create(password)

  end

  def is_password?(password)
    Bcrypt::Password.new(password).is_password?(password)
  end



end

W5D1/MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController


  def show
    @album = Album.find(params[:id])

    render :show
  end

  def edit

  end

  def new
    @album = Album.new

    render :new
  end

  def create
    @album = Album.new(user_params)

    if @album.save
      log_in_user!(@album)

      redirect_to user_url(@album)
    else
      @album.errors.full_messages
    end

  end



  private

  def user_params

    params.require(:album).permit(:band_id, :title, :year, :live)

  end

end

W5D1/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return nil if session[:session_token] == nil

    @current_user = User.find_by(session_token: session[:session_token])
  end

  def logged_in?

    !!current_user

  end

  def log_in_user!(user)
    @current_user = user

    session[:session_token] = user.reset_session_token!
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end


end

W5D1/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index

    @bands = Band.all

    render :index

  end

  def show
    @band = Band.find_by(params[:id])

    render :show
  end

  def new
    @band = Band.new

    render :new
  end


end

W5D1/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
      @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

      if @user.nil?
        render json: "wrong credentials"
      else
        log_in_user!(@user)

        redirect user_url(@user)
      end

    end

    def new
      @user = User.new

      render :new
    end

    def destroy


      log_out

      redirect_to new_session_url

    end

end

W5D1/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

    @users = User.all

    render :index

  end

  def show
    @user = User.find(params[:id])

    render :show
  end

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)

      redirect_to user_url(@user)
    else
      @user.errors.full_messages
    end

  end



  private

  def user_params

    params.require(:user).permit(:name, :email, :password)

  end

end

W5D1/MusicApp/app/views/albums/show.html.erb
<h1> <%= @album.name %> </h1>
<h3> <%= @album.year %> </h3>
<% if @album.live %>
<h3> Type: Live </h3>
<% else %>
<h3> Type: Studio </h3>
<% end %>

W5D1/MusicApp/app/views/bands/index.html.erb
<h2> All the Bands !!! </h2>
<h5> <a href = "<%=new_band_url%>"> -- Add a new Band -- </a> </h5>

<ol>
<% @bands.each do |band| %>

<li><%= band.name %></li>

<% end %>
</ol>

W5D1/MusicApp/app/views/bands/new.html.erb
<h1> Add a new Band! </h1>

<form action ="<%= bands_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="name"> Band Name </label>
  <input
    type = "text"
    name = "band[name]"
    id = "name"
   >


<br>
  <input type="submit" value= "Create">

   </form>

W5D1/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.nil? %>
    <small><a href = "<%=new_session_url%>"> Please log in to continue </a></small>

    <% else %>

    <small><%=("Welcome, #{current_user.name}")%> </small>

    <small> <form action="<%= session_url %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="delete">
            <input type="submit" value="Logout">

    </form> </small>

    <% end %>

    <%= yield %>
  </body>
</html>

W5D1/MusicApp/app/views/users/index.html.erb
<h1> Music App </h1>

<h3> Join our community now and Sign up! </h3>
<h5> (Members: <%=  @users.count %>) </h5>

<% @users.each do |user| %>
<%= user.name %>
<br>
<% end %>

W5D1/MusicApp/app/views/users/new.html.erb
<h1> Create a User! </h1>

<form action ="<%= users_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="name"> Name </label>
  <input
    type = "text"
    name = "user[name]"
    id = "name"
    value = "<% @user.name %>" >

<br>
  <label for="email"> E-Mail </label>
  <input
    type = "text"
    name = "user[email]"
    id = "email"
    value = "<% @user.email %>" >

<br>
  <label for="password"> Password </label>
  <input
    type = "text"
    name = "user[password]"
    id = "password"
     >

<br>
  <input type="submit" value= "Create">

   </form>